// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://orlxsliymaxvjliguxuv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ybHhzbGl5bWF4dmpsaWd1eHV2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIwOTMwNjIsImV4cCI6MjA4NzY2OTA2Mn0.rXLDX-KvnGplIv8qQqp4Gx5jnv5H7afp2WononyKGEc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});